// Code generated by protoc-gen-go.
// source: steering.proto
// DO NOT EDIT!

/*
Package steering is a generated protocol buffer package.

It is generated from these files:
	steering.proto

It has these top-level messages:
	Direction
	DriveReply
	Image
	ImageBytes
*/
package steering

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Direction is normalized delta x and y that corresponds to joystick position. Range should be between -100 and 100.
type Direction struct {
	Dx int32 `protobuf:"varint,1,opt,name=dx" json:"dx,omitempty"`
	Dy int32 `protobuf:"varint,2,opt,name=dy" json:"dy,omitempty"`
}

func (m *Direction) Reset()         { *m = Direction{} }
func (m *Direction) String() string { return proto.CompactTextString(m) }
func (*Direction) ProtoMessage()    {}

type DriveReply struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *DriveReply) Reset()         { *m = DriveReply{} }
func (m *DriveReply) String() string { return proto.CompactTextString(m) }
func (*DriveReply) ProtoMessage()    {}

type Image struct {
	Live bool `protobuf:"varint,1,opt,name=live" json:"live,omitempty"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}

type ImageBytes struct {
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (m *ImageBytes) Reset()         { *m = ImageBytes{} }
func (m *ImageBytes) String() string { return proto.CompactTextString(m) }
func (*ImageBytes) ProtoMessage()    {}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Driver service

type DriverClient interface {
	// Drive is a client-to-server stream providing direction.
	Drive(ctx context.Context, opts ...grpc.CallOption) (Driver_DriveClient, error)
	GetImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (Driver_GetImageClient, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) Drive(ctx context.Context, opts ...grpc.CallOption) (Driver_DriveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Driver_serviceDesc.Streams[0], c.cc, "/steering.Driver/Drive", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverDriveClient{stream}
	return x, nil
}

type Driver_DriveClient interface {
	Send(*Direction) error
	CloseAndRecv() (*DriveReply, error)
	grpc.ClientStream
}

type driverDriveClient struct {
	grpc.ClientStream
}

func (x *driverDriveClient) Send(m *Direction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *driverDriveClient) CloseAndRecv() (*DriveReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DriveReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) GetImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (Driver_GetImageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Driver_serviceDesc.Streams[1], c.cc, "/steering.Driver/GetImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverGetImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_GetImageClient interface {
	Recv() (*ImageBytes, error)
	grpc.ClientStream
}

type driverGetImageClient struct {
	grpc.ClientStream
}

func (x *driverGetImageClient) Recv() (*ImageBytes, error) {
	m := new(ImageBytes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Driver service

type DriverServer interface {
	// Drive is a client-to-server stream providing direction.
	Drive(Driver_DriveServer) error
	GetImage(*Image, Driver_GetImageServer) error
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_Drive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DriverServer).Drive(&driverDriveServer{stream})
}

type Driver_DriveServer interface {
	SendAndClose(*DriveReply) error
	Recv() (*Direction, error)
	grpc.ServerStream
}

type driverDriveServer struct {
	grpc.ServerStream
}

func (x *driverDriveServer) SendAndClose(m *DriveReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *driverDriveServer) Recv() (*Direction, error) {
	m := new(Direction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Driver_GetImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Image)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).GetImage(m, &driverGetImageServer{stream})
}

type Driver_GetImageServer interface {
	Send(*ImageBytes) error
	grpc.ServerStream
}

type driverGetImageServer struct {
	grpc.ServerStream
}

func (x *driverGetImageServer) Send(m *ImageBytes) error {
	return x.ServerStream.SendMsg(m)
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "steering.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Drive",
			Handler:       _Driver_Drive_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetImage",
			Handler:       _Driver_GetImage_Handler,
			ServerStreams: true,
		},
	},
}
