// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: steering.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction is normalized delta x and y that corresponds to joystick position. Range should be between -100 and 100.
type Direction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dx            int32                  `protobuf:"varint,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,2,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Direction) Reset() {
	*x = Direction{}
	mi := &file_steering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Direction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Direction) ProtoMessage() {}

func (x *Direction) ProtoReflect() protoreflect.Message {
	mi := &file_steering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Direction.ProtoReflect.Descriptor instead.
func (*Direction) Descriptor() ([]byte, []int) {
	return file_steering_proto_rawDescGZIP(), []int{0}
}

func (x *Direction) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *Direction) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         int32                  `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`
	DistFront     int32                  `protobuf:"varint,2,opt,name=distFront,proto3" json:"distFront,omitempty"`
	DistRear      int32                  `protobuf:"varint,3,opt,name=distRear,proto3" json:"distRear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_steering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_steering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_steering_proto_rawDescGZIP(), []int{1}
}

func (x *Telemetry) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Telemetry) GetDistFront() int32 {
	if x != nil {
		return x.DistFront
	}
	return 0
}

func (x *Telemetry) GetDistRear() int32 {
	if x != nil {
		return x.DistRear
	}
	return 0
}

var File_steering_proto protoreflect.FileDescriptor

var file_steering_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x73, 0x74, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x74, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x2b, 0x0a, 0x09, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x64, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x64, 0x79, 0x22, 0x5b, 0x0a, 0x09, 0x54, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x73, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64,
	0x69, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x72, 0x32, 0x41, 0x0a, 0x06, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x37,
	0x0a, 0x05, 0x44, 0x72, 0x69, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x73, 0x74, 0x65, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x2e, 0x73,
	0x74, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x77, 0x65, 0x6c, 0x6b, 0x6f, 0x77, 0x61, 0x6c,
	0x61, 0x6b, 0x2f, 0x62, 0x65, 0x72, 0x72, 0x79, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_steering_proto_rawDescOnce sync.Once
	file_steering_proto_rawDescData []byte
)

func file_steering_proto_rawDescGZIP() []byte {
	file_steering_proto_rawDescOnce.Do(func() {
		file_steering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steering_proto_rawDesc), len(file_steering_proto_rawDesc)))
	})
	return file_steering_proto_rawDescData
}

var file_steering_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steering_proto_goTypes = []any{
	(*Direction)(nil), // 0: steering.Direction
	(*Telemetry)(nil), // 1: steering.Telemetry
}
var file_steering_proto_depIdxs = []int32{
	0, // 0: steering.Driver.Drive:input_type -> steering.Direction
	1, // 1: steering.Driver.Drive:output_type -> steering.Telemetry
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steering_proto_init() }
func file_steering_proto_init() {
	if File_steering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steering_proto_rawDesc), len(file_steering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steering_proto_goTypes,
		DependencyIndexes: file_steering_proto_depIdxs,
		MessageInfos:      file_steering_proto_msgTypes,
	}.Build()
	File_steering_proto = out.File
	file_steering_proto_goTypes = nil
	file_steering_proto_depIdxs = nil
}
