// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: steering.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Driver_Drive_FullMethodName = "/steering.Driver/Drive"
)

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The driving service definition.
type DriverClient interface {
	// Drive is a client-to-server stream providing direction.
	Drive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Direction, Telemetry], error)
}

type driverClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverClient(cc grpc.ClientConnInterface) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) Drive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Direction, Telemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Driver_ServiceDesc.Streams[0], Driver_Drive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Direction, Telemetry]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driver_DriveClient = grpc.BidiStreamingClient[Direction, Telemetry]

// DriverServer is the server API for Driver service.
// All implementations must embed UnimplementedDriverServer
// for forward compatibility.
//
// The driving service definition.
type DriverServer interface {
	// Drive is a client-to-server stream providing direction.
	Drive(grpc.BidiStreamingServer[Direction, Telemetry]) error
	mustEmbedUnimplementedDriverServer()
}

// UnimplementedDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServer struct{}

func (UnimplementedDriverServer) Drive(grpc.BidiStreamingServer[Direction, Telemetry]) error {
	return status.Errorf(codes.Unimplemented, "method Drive not implemented")
}
func (UnimplementedDriverServer) mustEmbedUnimplementedDriverServer() {}
func (UnimplementedDriverServer) testEmbeddedByValue()                {}

// UnsafeDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServer will
// result in compilation errors.
type UnsafeDriverServer interface {
	mustEmbedUnimplementedDriverServer()
}

func RegisterDriverServer(s grpc.ServiceRegistrar, srv DriverServer) {
	// If the following call pancis, it indicates UnimplementedDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Driver_ServiceDesc, srv)
}

func _Driver_Drive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DriverServer).Drive(&grpc.GenericServerStream[Direction, Telemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Driver_DriveServer = grpc.BidiStreamingServer[Direction, Telemetry]

// Driver_ServiceDesc is the grpc.ServiceDesc for Driver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Driver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steering.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Drive",
			Handler:       _Driver_Drive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "steering.proto",
}
